---
title: "R Notebook"
output: html_notebook
---
---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readr)
library(lubridate)
library(ggplot2)
library(dplyr)
library(leaps)
library (pracma)
library(readxl)

umsatzdaten <- read_csv("data/umsatzdaten_gekuerzt.csv")
kiwo<- read_csv("data/kiwo.csv")
feiertage <- read_csv("data/feiertage.csv")
Zeiten <- read_excel("data/Zeiten.xlsx")
feiertage <- read_csv("data/feiertage.csv")
wetter <- read_csv("data/wetter.csv")
niederschlagsmenge <- read_csv("data/Niederschlagsmenge.csv")
sonnenschein <- read_csv("data/Sonnenscheindauer.csv")

merger<-left_join(umsatzdaten,kiwo)
Zeiten <- Zeiten %>% 
mutate(Datum = as.Date(Datum)) 
merger <- merger %>% 
mutate(Datum = as.Date(Datum)) 
merger2<-left_join(merger,Zeiten, by='Datum')
merger2[is.na(merger2)]<-0
merger2$wochentag <- weekdays(merger2$Datum)
merger3<-left_join(merger2,feiertage)
merger3[is.na(merger3)]<-0
merger4<-left_join(merger3, niederschlagsmenge, by='Datum')
merger5<-left_join(merger4, sonnenschein, by='Datum')


 
final<-left_join (merger5, wetter)

#merger5<-left_join(merger4,)
#final<-left_join(merger4, merger1_2)
View(final)

#write.csv2(final, "dateiname.csv")
```



```{r}
#Dummy für Wochentage, Stena Line fährt jeden Tag

final%>%
mutate(Dummy = ifelse(wochentag=='Dienstag', "1", "0"))

final%>%
lag(feiertage, k=1)
  

movag<-movavg(wetter$Temperatur, 7, type=c("s"))


####UNDER CONSTRUCTION####
#Moving Average
# Function ma() calculates the moving average of order n
ma <- function(x, n = 7) { filter(x, rep(1/n,n), sides = 7, method = "convolution") }

for (Datum in final) {
  
}

movingaverage <- data.frame(final$Datum, "Moving Average")
# Calculate moving averages of order 7
ma7 <- ma(final$Umsatz, 7)

```

Balkendiagramm Beispiel 
```{r}
wetter <- read_csv("data/wetter.csv")
sonne <- read_csv("data/Sonnenscheindauer.csv")

View (wetter)
View(sonne)

```



```{r}
wetter$month<-month(as.POSIXlt(wetter$Datum, format="%d/%m/%Y"))

wetter$Monate<-month.abb[wetter$month]

wetter$Monate <- factor(wetter$Monate, levels=c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dezc"))
View (wetter)

```



```{r}
sonne$month<-month(as.POSIXlt(sonne$Datum, format="%d/%m/%Y"))

sonne$Monate<-month.abb[sonne$month]

sonne$Monate <- factor(sonne$Monate, levels=c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))
View (sonne)

```


```{r}
my_sum <- wetter %>%
  group_by(Monate) %>%
  summarise(
    n=n(),
    mean=mean(Temperatur),
    sd=sd(Temperatur)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))

# Confidence Interval
ggplot(my_sum) +
  geom_bar( aes(x=Monate, y=mean), stat="identity", fill="forestgreen", alpha=0.5) +
  geom_errorbar( aes(x=Monate, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="orange", alpha=0.9, size=1.5) +
  ggtitle("Durchschnittliche Monatstemperatur")

```


```{r}
my_sum <- sonne %>%
  group_by(Monate) %>%
  summarise(
    n=n(),
    mean=mean(Sonnenscheindauer),
    sd=sd(Sonnenscheindauer)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))

# Confidence Interval
ggplot(my_sum) +
  geom_bar( aes(x=Monate, y=mean), stat="identity", fill="forestgreen", alpha=0.5) +
  geom_errorbar( aes(x=Monate, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="orange", alpha=0.9, size=1.5) +
  ggtitle("Durchschnittliche Sonnenscheindauer")

```

```

Sollten einen Dummy für vor oder nach Feiertag nehmen, Tage vor dem eigentlichen verkauf mit reinnehmen

Lineare Regression
```{r}
mod<- lm(Umsatz~KielerWoche+ Ferien+ wochentag + Feiertag + Temperatur+as.factor(Warengruppe)+ Bewoelkung+ Vor+ Nach,final)
summary(mod)

```



Subsets
```{r}
y <- regsubsets(Umsatz ~ ., final, nvmax=10)
summary(y)

```

